[package]
name = "grump"
version = "0.1.0"
authors = ["Matthew Auld <matthew@matthewauld.ca>"]
edition = "2018"

[dependencies]
pulldown-cmark = { version = "0.5", default-features = false }
regex = "1"
structopt = { version = "0.2" }
glob = "0.3.0"
